#!/usr/bin/env bash

source "$(dirname $0)/global"

sudo -v

pushd ${HOME} > /dev/null && trap 'popd > /dev/null' EXIT HUP INT QUIT TERM

${INSTALLER}/setup-brew
${INSTALLER}/setup-fonts
${INSTALLER}/setup-shell
${INSTALLER}/setup-rcfiles
${INSTALLER}/setup-ssh
${INSTALLER}/setup-sub
source ${DOTFILES}/lib/macos/env

# Customize OSX
${INSTALLER}/setup-system
${INSTALLER}/setup-sudo-fingerprint

exit 0
