#!/usr/bin/env bash

export homebrew_prefix=${HOMEBREW_PREFIX:-/usr/local};

# Customize my paths
if [ -f "/etc/paths.original" ]
then
  sudo mv /etc/paths{.original,}
fi

sudo cp /etc/paths /etc/paths.d/system;
sudo mv /etc/paths{,.original};
echo "${homebrew_prefix}/bin" | sudo tee /etc/paths.d/homebrew;
echo "${homebrew_prefix}/sbin" | sudo tee -a /etc/paths.d/homebrew;

# reset $PATH
eval $(/usr/libexec/path_helper -s);

# Make custom shells available
if [ -f "/etc/shells.original" ]
then
  sudo mv /etc/shells{.original,}
fi

sudo cp /etc/shells{,.original};

[[ $(grep "${homebrew_prefix}/bin/bash" /etc/shells) ]] || \
  echo "${homebrew_prefix}/bin/bash" | sudo tee -a /etc/shells

[[ $(grep "${homebrew_prefix}/bin/zsh" /etc/shells) ]] || \
  echo "${homebrew_prefix}/bin/zsh" | sudo tee -a /etc/shells

#install Oh My Zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

#Install cobalt2 theme
wget https://raw.githubusercontent.com/wesbos/Cobalt2-iterm/master/cobalt2.zsh-theme -P ~/.oh-my-zsh/themes

#Install some plugins
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-completions
git clone https://github.com/zsh-users/zsh-syntax-highlighting ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
