#!/usr/bin/env bash

source "$(dirname $0)/global"

if [ -z $1 ]; then
  installer_path=${INSTALLER}
else
  installer_path=$1
fi

# ssh
mkdir -p ${HOME}/.ssh
cp ${installer_path}/ssh_config ${HOME}/.ssh/config
chmod -R 700 ${HOME}/.ssh
