#!/usr/bin/env bash

source "$(dirname $0)/global"

if [ -z $1 ]; then
  rcfiles_dir=${RCFILES_PATH}
else
  rcfiles_dir=$1
fi

# Create linked files
for f in ${rcfiles_dir}/*
do
  target=${HOME}/.${f##*/}
  if [ -L ${target} ]
  then
    rm -rf $target
  elif [ -f ${target} ]
  then
    echo "${target} already exists and is not a link"
  fi
  ln -sf ${f} $target
done