#!/usr/bin/env zsh

export DOTFILES=${HOME}/.dotfiles
export HOMEBREW_PREFIX=${HOMEBREW_PREFIX:-/usr/local}

# Fix PATH
if [ -x /usr/libexec/path_helper ]
then
  PATH=""
  eval `/usr/libexec/path_helper -s`
fi

#zsh configuration
export ZSH=$HOME/.oh-my-zsh
plugins=(git colored-man colorize pip python brew osx zsh-syntax-highlighting zsh-autosuggestions zsh-completions zsh-syntax-highlighting)
ZSH_THEME="agnoster"
ZSH_DISABLE_COMPFIX=true
source $ZSH/oh-my-zsh.sh
export EDITOR='vim'

#last steps
export DOTFILES=$HOME/.dotfiles

# My env customization env
source "$DOTFILES/lib/macos/env"