#!/usr/bin/env bash

# System
alias ls="ls -G -h"
alias ll="ls -l"
alias la="ls -lA"
alias lah="ls -lah"

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias week="date +%V"
alias count="ls -l | wc -l"

alias reload!='. ~/.zshrc'

# Searching
alias grep="grep -v 'grep --color=auto -i' | grep --color=auto -i"
alias psg="ps aux | grep"

# Process
alias ctop="htop -s PERCENT_CPU"
alias mtop="htop -s PERCENT_MEM"
