#!/usr/bin/env bash

export DOTFILES=$(dirname $0);

printf "Installing dotfiles\n"
printf "Instalation located at $DOTFILES\n\n"


if [ $(uname) = 'Darwin' ]; then
  echo "Mac OS detected"
  INSTALLERS_PATH="$DOTFILES/installers/macos"
else
  echo "Linux detected"
  $DOTFILES/linux/setup;
  exit 0;
fi

if [ -z $1 ]; then
  echo "Running all installers"
  for installer in $(find "$INSTALLERS_PATH" -type file -depth 1 | sort); do
    printf "\n\n>>> Running: $installer\n"
    $installer
  done
else
  installer="$INSTALLERS_PATH/$1"
  printf "\n\n>>> Running: $installer\n"
  $installer
fi

printf "\n\nFinished successfully\n\n"
exit 0;