#!/usr/bin/env bash

export DOTFILES=$(dirname $0);

printf "Installing dotfiles\n"
printf "Instalation located at $DOTFILES\n\n"


if [ $(uname) = 'Darwin' ]; then
  echo "Mac OS detected"
  INSTALLERS_PATH="$DOTFILES/installers/macos"
elif [ "$(uname -s)" = "Linux" ]; then
  INSTALLERS_PATH="$DOTFILES/installers/linux"
else
  echo "OS not supported."
  echo "Aborting."
  exit 1
fi

if [ -z $1 ]; then
  echo "Running all installers"
  for installer in $(find "$INSTALLERS_PATH" -maxdepth 1 -type f | sort); do
    printf "\n\n>>> Running: $installer\n"
    $installer
  done
else
  installer="$INSTALLERS_PATH/$1"
  printf "\n\n>>> Running: $installer\n"
  $installer
fi

printf "\n\nFinished successfully\n\n"
exit 0;