#!/usr/bin/env zsh
echo "$(gdate +"%T.%3N"): Initializing a new session"

export DOTFILES=${HOME}/.dotfiles

echo "$(gdate +"%T.%3N"): Rebuilding PATH"
if [ -x /usr/libexec/path_helper ]; then
  PATH=""
  eval `/usr/libexec/path_helper -s`
fi

echo "$(gdate +"%T.%3N"): Loading my env customization"
source "$DOTFILES/env/macos"