#!/usr/bin/env bash

source "$(dirname $0)/global"

# Create linked files
for f in ${INSTALLER}/rcfiles/*
do
  target=${HOME}/.${f##*/}
  if [ -L ${target} ]
  then
    rm -rf $target
  elif [ -f ${target} ]
  then
    echo "${target} already exists and is not a link"
  fi
  ln -sf ${f} $target
done

# ssh
mkdir -p ${HOME}/.ssh
cp ${INSTALLER}/ssh_config ${HOME}/.ssh/config
chmod -R 700 ${HOME}/.ssh
