#!/usr/bin/env bash

# System
alias ls="ls -G -h"
alias ll="ls -l"
alias la="ls -lA"
alias lah="ls -lah"

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias week="date +%V"
alias count="ls -l | wc -l"

# Searching
alias grep="grep --color=auto -i"

# Process
alias ctop="htop -s PERCENT_CPU"
alias mtop="htop -s PERCENT_MEM"

# Functions

# Make a directory and cd into it
mkd ()
{
  mkdir -p -- "$1" &&
    cd -P -- "$1"
}