#!/usr/bin/env bash

echo "$(date +"%T.%3N"): Initializing a new session"

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=100000
HISTFILESIZE=1000000000

export DOTFILES=${HOME}/.dotfiles

# My env customization env
source "$DOTFILES/env/linux"
