#!/usr/bin/env bash

# softwareupdate -ia

#################### System Wide #####################

# Disable Resume Windows after restart
defaults write com.apple.systempreferences NSQuitAlwaysKeepsWindows -bool false

# Always show scroll bars
defaults write NSGlobalDomain AppleShowScrollBars -string "Always"

# Save to disk (not to iCloud) by default
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# Disable the “Are you sure you want to open this application?” dialog
defaults write com.apple.LaunchServices LSQuarantine -bool false

# Disable continuous spell checking
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "continuousSpellCheckingEnabled" -bool false

# Enable subpixel font rendering on non-Apple LCDs
# Reference: https://github.com/kevinSuttle/macOS-Defaults/issues/17#issuecomment-266633501
defaults write NSGlobalDomain AppleFontSmoothing -int 1

##################### Energy #########################

# Sleep the display after 15 minutes
sudo pmset -a displaysleep 15 2> /dev/null
# Set display sleep to 5 minutes on battery
sudo pmset -b displaysleep 5 2> /dev/null
# Disable machine sleep while charging
sudo pmset -c sleep 0 2> /dev/null
# Set machine sleep to 5 minutes on battery
sudo pmset -b sleep 10 2> /dev/null
# Set standby delay to 24 hours (default is 1 hour)
sudo pmset -a standbydelay 86400 2> /dev/null
sudo systemsetup -setcomputersleep Off 2> /dev/null
# Hibernation mode
# 0: Disable hibernation (speeds up entering sleep mode)
# 3: Copy RAM to disk so the system state can still be restored in case of a
#    power failure.
sudo pmset -a hibernatemode 0 2> /dev/null

##################### Locale #########################

# Note: if you’re in the US, replace `EUR` with `USD`, `Centimeters` with
# `Inches`, `en_GB` with `en_US`, and `true` with `false`.
defaults write NSGlobalDomain AppleLanguages -array "en"
defaults write NSGlobalDomain AppleLocale -string "en_US@currency=EUR"
defaults write NSGlobalDomain AppleMeasurementUnits -string "Centimeters"
defaults write NSGlobalDomain AppleMetricUnits -bool true

##################### Keyboard #######################

# Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)
defaults write -g AppleKeyboardUIMode -int 3
# Turn on key repeat (Disable hold modifier)
defaults write -g ApplePressAndHoldEnabled -bool false
defaults write -g InitialKeyRepeat -int 15
defaults write -g KeyRepeat -int 2
# Disable automatic capitalization
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false
# Disable smart dashes
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
# Disable automatic period substitution
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false
# Enable auto replacement
defaults write -g WebAutomaticTextReplacementEnabled -int 1
# Disable auto-correct
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# Layout
defaults write -g com.apple.HIToolbox '{
  AppleCurrentKeyboardLayoutInputSourceID = "com.apple.keylayout.US";
  AppleEnabledInputSources = ();
  AppleInputSourceHistory = ();
  AppleSelectedInputSources = ();
}'

##################### Finder #########################

# Use Finders list view as the default view mode
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"
# Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -int 0
# Show all filename extensions in Finder
defaults write -g AppleShowAllExtensions -int 1
# Show path bar
defaults write com.apple.finder ShowPathbar -int 1
# Show status bar
defaults write com.apple.finder ShowStatusBar -int 1
# Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -int 1
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -int 1
# Expand print panel by default
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -int 1
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -int 1
# Increase window resize speed for Cocoa applications
defaults write NSGlobalDomain NSWindowResizeTime -float 0.001
# Set sidebar icon size to small
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 1
# Dark mode
defaults write NSGlobalDomain AppleInterfaceStyle -string "Dark"
defaults write NSGlobalDomain AppleShowAllExtensions -int 1
# Disable window animations and Get Info animations
defaults write com.apple.finder DisableAllAnimations -int 1
# Disable the warning before emptying the Trash
defaults write com.apple.finder WarnOnEmptyTrash -int 0
# When performing a search, search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
# Set Home as the default location for new Finder windows
defaults write com.apple.finder NewWindowTarget -string "PfLo"
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}"
# Prevent Photos from opening automatically when devices are plugged in
defaults -currentHost write com.apple.ImageCapture disableHotPlug -int 1
# Save screenshots to the desktop
defaults write com.apple.screencapture location -string "${HOME}/Desktop"
# Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
defaults write com.apple.screencapture type -string "png"
# Disable shadow in screenshots
defaults write com.apple.screencapture disable-shadow -bool true
# Show icons for hard drives, servers, and removable media on the desktop
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true
# Show hidden files by default
defaults write com.apple.finder AppleShowAllFiles -bool true
# Avoid creating .DS_Store files on network or USB volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
# Automatically open a new Finder window when a volume is mounted
defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true
defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true
# Show the ~/Library folder
sudo chflags nohidden ~/Library
# Show the /Volumes folder
sudo chflags nohidden /Volumes

##################### Menu Bar #######################

# Set time to 24h format
defaults delete com.apple.menuextra.clock

defaults write NSGlobalDomain AppleICUForce24HourTime  -bool true
defaults write com.apple.menuextra.clock DateFormat -string 'EEE MMM d  H:mm:ss'

##################### Sound ##########################

# Disable beep
defaults write NSGlobalDomain com.apple.sound.beep.flash -int 0
defaults write NSGlobalDomain com.apple.sound.uiaudio.enabled -int 0

# Disable the sound effects on boot
sudo nvram SystemAudioVolume=" "
# Stop iTunes from responding to the keyboard media keys
launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist 2> /dev/null

##################### Dock ###########################

# Reset Launchpad, but keep the desktop wallpaper intact
find "${HOME}/Library/Application Support/Dock" -name "*-*.db" -maxdepth 1 -delete
# faster animations on expose
defaults write com.apple.dock expose-animation-duration -float 0.1
defaults write NSGlobalDomain NSWindowResizeTime -float 0.001
# Autohide dock
defaults write com.apple.dock autohide -int 1
defaults write com.apple.Dock autohide-delay -float 0.5
# Set dock default size
defaults write com.apple.dock tilesize -int 56
# Minimize windows into their application’s icon
defaults write com.apple.dock minimize-to-application -int 1
# Wipe all (default) app icons from the Dock
defaults write com.apple.dock persistent-apps -array
# Disable dashboard
defaults write com.apple.dashboard mcx-disabled -int 1
# Don’t automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -int 0
# Reset LaunchPad
defaults write com.apple.dock ResetLaunchPad -bool true

##################### Security #######################

# Require password immediately after sleep or screen saver begins
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0
# Check for software updates daily, not just once per week
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1
# Install System data files & security updates
defaults write com.apple.SoftwareUpdate CriticalUpdateInstall -int 1
# Disable java on safari
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabled -bool false
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabledForLocalFiles -bool false
# Enable “Do Not Track”
defaults write com.apple.Safari SendDoNotTrackHTTPHeader -bool true

##################### Safari #########################

# Privacy: don’t send search queries to Apple
defaults write com.apple.Safari UniversalSearchEnabled -bool false
defaults write com.apple.Safari SuppressSearchSuggestions -bool true
# Press Tab to highlight each item on a web page
defaults write com.apple.Safari WebKitTabToLinksPreferenceKey -bool true
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2TabsToLinks -bool true
# Enable the Develop menu and the Web Inspector in Safari
defaults write com.apple.Safari IncludeDevelopMenu -bool true
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true
# Show the full URL in the address bar (note: this still hides the scheme)
defaults write com.apple.Safari ShowFullURLInSmartSearchField -bool true
# Disable AutoFill
defaults write com.apple.Safari AutoFillPasswords -bool false
defaults write com.apple.Safari AutoFillCreditCardData -bool false

##################### Chrome #########################

# Does not keep a process to check for chrome updates
defaults write com.google.Keystone.Agent checkInterval 0

# Remove swipe to go back
defaults write com.google.Chrome AppleEnableMouseSwipeNavigateWithScrolls -bool false
defaults write com.google.Chrome AppleEnableSwipeNavigateWithScrolls -bool false

######################################################

# Kill affected applications
for app in Finder Dock SystemUIServer Photos Messages
do
  killall "$app" >/dev/null 2>&1
done

echo "Done. Note that some of these changes require a logout/restart to take effect."

