#!/usr/bin/env zsh

export DOTFILES=${HOME}/.dotfiles

#zsh configuration
export ZSH=$HOME/.oh-my-zsh
plugins=(git colored-man-pages colorize pip python osx zsh-syntax-highlighting zsh-autosuggestions zsh-completions)
ZSH_THEME="agnoster"
ZSH_DISABLE_COMPFIX=true
source $ZSH/oh-my-zsh.sh
export EDITOR='vim'

#last steps
export DOTFILES=$HOME/.dotfiles

# My env customization env
source "$DOTFILES/lib/linux/env"